In [1]:
#Creating 1D and 2D arrays
import numpy as np
numbers = [1, 2, 3, 4, 5]
numbers = np.array(numbers)
print("One dimensional array : ", numbers)

One dimensional array :  [1 2 3 4 5]


In [2]:
numbers = [1, 2, 3, 4, 5], ["hello", "world"]
numbers = np.array(numbers)
print("Two dimensional array : ", numbers)

Two dimensional array :  [list([1, 2, 3, 4, 5]) list(['hello', 'world'])]


<ipython-input-2-08a554ea7de9>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  numbers = np.array(numbers)


In [3]:
#Eye function in NumPy
eye_mat = np.eye(3)
print("One across diagonals : \n\n", eye_mat)

One across diagonals : 

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#Random numbers from 1 to 100 printing 10
random_print = np.random.randint(0, 100, 10)
print("Random numbers from 1 to 100 printing 10 : \n\n ", random_print)

Random numbers from 1 to 100 printing 10 : 

  [67 26 63 80 39 69 49 85 17 40]


In [5]:
#Printing the last element in array
names = np.array(["Abhishek", "Rahul", "Bhavesh", "Beth"])
print("Last element of the array is ", names[-1])

Last element of the array is  Beth


In [7]:
#Printing 3rd element of the 2nd row
numbers = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(numbers[1, 2])

6


In [9]:
#Using an array of 5 x 5, insert numbers from 1 to 25
numbers = np.arange(1, 26).reshape(5, 5)
print(numbers)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [11]:
#Replace all even numbers in array
numbers = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
numbers[numbers % 2 == 0] = 5
print(numbers)

[5 1 5 3 5 5 5 7 5 9 5]


In [13]:
#Converting a 1D array into 2D array
numbers = np.arange(10)
print(numbers)
print("Reshaped into 2 dimensions : \n")
numbers.reshape(2, -1)

[0 1 2 3 4 5 6 7 8 9]
Reshaped into 2 dimensions : 



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
#Printing the common elements in 2 arrays
x = np.array([10, 6, 30, 45, 2])
y = np.array([36, 85, 10, 2, 7, 30])
np.intersect1d(x, y)

array([ 2, 10, 30])

In [22]:
#Printing elements from 4 to 10 in array
numbers = np.arange(11)
print(numbers)
numbers[(numbers >= 4) & (numbers <= 10)]

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 4,  5,  6,  7,  8,  9, 10])

In [23]:
import pandas as pd

In [25]:
#Sample series using Dictionary and Pandas
sample_dict = {"x":1, "y":2, "z":3}
the_series = pd.Series(sample_dict)
print(the_series)

x    1
y    2
z    3
dtype: int64


In [26]:
#Assigning names to the series index
sample_series = pd.Series(list('1234567890'))
sample_series.name = 'numbers'
sample_series.head()

0    1
1    2
2    3
3    4
4    5
Name: numbers, dtype: object

In [29]:
#printing numbers that are present only in one series
first_series = pd.Series([1, 2, 3, 4, 5, 6])
second_series = pd.Series([5, 6, 7, 8])
second_series[~second_series.isin(first_series)]

2    7
3    8
dtype: int64

In [30]:
#Converting NumPy arrays into Pandas dataframe
sample_series = pd.Series(np.random.randint(1, 30, 25))
data_frame = pd.DataFrame(sample_series.values.reshape(5, 5))
print(data_frame)

    0   1   2   3   4
0  25   4  20  17  20
1  19   3  13  20  17
2  11   8  26  22  14
3  20  27   3  10  18
4  21   9  19  23  17
